CarRental.Presentation/Controllers/CarController.cs
using AutoMapper;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using CarRental.Presentation.Models;
using CarRental.Application.Dto;
using Wypożyczalnia_samochodów_online.Extensions;
using CarRental.Application.CQRS.Queries.CarQueries.GetAllCars;
using CarRental.Application.CQRS.Queries.CarQueries.GetCarDetails;
using CarRental.Application.CQRS.Commands.Car.CreateCar;
using CarRental.Application.CQRS.Commands.Car.EditCar;
using CarRental.Application.CQRS.Commands.Car.DeleteCar;

namespace CarRental.Presentation.Controllers;


[Authorize(Roles = "Admin")]
public class CarController : Controller
{

    private readonly IMapper _mapper;
    private readonly IMediator _mediator;

    public CarController(IMapper mapper, IMediator mediator)
    {
        _mapper = mapper;
        _mediator = mediator;
    }

    [AllowAnonymous]
    [HttpGet]
    public async Task<IActionResult> Index(CancellationToken cancellation)
    {
        var carDtos = await _mediator.Send(new GetAllCarsQuery(), cancellation);

        var viewModel = _mapper.Map<ICollection<CreateCarViewModel>>(carDtos);

        return View(viewModel);
    }

    [AllowAnonymous]
    [HttpGet]
    public async Task<IActionResult> Details(int id, CancellationToken cancellation)
    {
        var detailsDto = await _mediator.Send(new CarDetailsQuery(id), cancellation);
        if (detailsDto == null)
        {
            return NotFound();
        }
        var viewModel = _mapper.Map<CreateCarViewModel>(detailsDto);

        return View(viewModel);
    }

    [HttpGet] // Admin
    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken] // Admin
    public async Task<IActionResult> Create(CreateCarViewModel carViewModel,
        CancellationToken cancellation)
    {
        if (ModelState.IsValid)
        {
            var command = new CreateCarCommand
            {
                CarDto = _mapper.Map<CarDto>(carViewModel)
            };

            command.CarDto.Images = carViewModel.Images ?? new List<IFormFile>();

            await _mediator.Send(command, cancellation);

            this.SetNotification("success", $"Car {command.CarDto.Brand}" +
                " " + $"{command.CarDto.Model} has been added successfully.");

            return RedirectToAction(nameof(Index));
        }

        return View(carViewModel);
    }


    [HttpGet]
    public async Task<IActionResult> Edit(int id, CancellationToken cancellation)
    {
;
        var car =  await _mediator.Send(new CarDetailsQuery(id), cancellation);

        var editViewModel = _mapper.Map<EditCarViewModel>(car);

        return View(editViewModel);
    }


    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, EditCarViewModel editCarViewModel,
        CancellationToken cancellation)
    {
        if (ModelState.IsValid)
        {
            var command = new EditCarCommand
            {
                Id = id,
                CarDto = _mapper.Map<CarDto>(editCarViewModel)
            };

            command.CarDto.Images = editCarViewModel.NewImages ?? new List<IFormFile>();

            await _mediator.Send(command, cancellation);

            this.SetNotification("success", $"Car {command.CarDto.Brand}" +
                " " + $"{command.CarDto.Model} has been updated successfully.");

            return RedirectToAction(nameof(Index));
        }
        return View(editCarViewModel);
    }
  

    [HttpGet]
    public async Task<IActionResult> Delete(int id, CancellationToken cancellation)
    {
        var car = await _mediator.Send(new CarDetailsQuery(id), cancellation);

        return View(car);
    }

  
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id, CancellationToken cancellation)
    {
        var car = await _mediator.Send(new CarDetailsQuery(id), cancellation);

        var command = new DeleteCarCommand() { Id = id };

        await _mediator.Send(command, cancellation);

        return RedirectToAction(nameof(Index));
    }
}

CarRental.Presentation/Controllers/ReservationController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MediatR;
using CarRental.Presentation.Models;
using AutoMapper;
using CarRental.Application.CQRS.Queries.ReservationQueries.GetMyReservations;
using CarRental.Application.CQRS.Commands.Reservation.CreateReservation;
using CarRental.Application.CQRS.Queries.ReservationQueries.GetReservationDetails;

namespace CarRental.Presentation.Controllers;

[Authorize] 
public class ReservationController : Controller
{
    private readonly UserManager<IdentityUser> _userManager; 
    private readonly IMediator _mediator;
    private readonly IMapper _mapper;

    public ReservationController(UserManager<IdentityUser> userManager,
        ILogger<ReservationController> logger, IMediator mediator, IMapper mapper)
    {
        _mediator = mediator;
        _userManager = userManager;
        _mapper = mapper;
    }
    

    [HttpGet]
    public async Task<IActionResult> MyReservations(CancellationToken cancellation)
    {
        var reservationsDto = await _mediator.Send(new GetMyReservationQuery(), cancellation);

        var viewModel = _mapper.Map<ICollection<MyReservationsViewModel>>(reservationsDto);

        return View(viewModel);
    }

    
    [HttpGet]
    public IActionResult Create(int carId, CreateReservationViewModel createReservationViewModel)
    {
        createReservationViewModel = new CreateReservationViewModel
        {
            CarId = carId, 
            StartDate = DateTime.Today, 
            EndDate = DateTime.Today.AddDays(1) 
        }; 
        return View(createReservationViewModel);
    }


    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(CreateReservationViewModel createReservationViewModel,
        CancellationToken cancellation)
    {

        if (!ModelState.IsValid)
        {    
            return View(createReservationViewModel);
        }

        try
        {
            // ViewModel -> Command
            var command = new CreateReservationCommand
            {
                CarId = createReservationViewModel.CarId,
                StartDate = createReservationViewModel.StartDate,
                EndDate = createReservationViewModel.EndDate
            };

            await _mediator.Send(command, cancellation);
            return RedirectToAction(nameof(MyReservations));
        }
        catch (Exception ex)
        {
            ModelState.AddModelError("", ex.Message);
            return View(createReservationViewModel);
        }
    }

 
    [HttpGet]
    public async Task<IActionResult> Details(int id)
    {
        var reservation = await _mediator.Send(new GetReservationDetailsQuery { Id = id });

        return View(reservation);
    }
}

CarRental.Presentation/Views/Car/Create.cshtml
@model CarRental.Presentation.Models.CreateCarViewModel

<h2>Create car</h2>

<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post" enctype="multipart/form-data">
            @Html.AntiForgeryToken() <!-- CSRF -->

            <div class="form-group mb-3">
                <label asp-for="Brand">Brand</label>
                <input class="form-control" type="text" asp-for="Brand" />
                <span asp-validation-for="Brand" class="text-danger"></span>
            </div>

            <div class="form-group mb-3">
                <label asp-for="Model">Model</label>
                <input class="form-control" type="text" asp-for="Model" />
                <span asp-validation-for="Model" class="text-danger"></span>
            </div>

            <div class="form-group mb-3">
                <label asp-for="PricePerDay">Price per day</label>
                <input class="form-control" type="text" asp-for="PricePerDay" />
                <span asp-validation-for="PricePerDay" class="text-danger"></span>
            </div>

            <div class="form-group mb-3">
                <label asp-for="IsAvailable">Is Available</label>
                <input asp-for="IsAvailable" type="checkbox" />
            </div>

            <div class="form-group mb-3">
                <label asp-for="Images">Upload Images</label>
                <input multiple class="form-control" type="file" asp-for="Images" />
                <span asp-validation-for="Images" class="text-danger"></span>
            </div>

            <div class="form-group mb-3">
                <label asp-for="Description">Description</label>
                <input class="form-control" type="text" asp-for="Description"/>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <div class="form-group mb-3">
                <label asp-for="Engine">Engine</label>
                <input class="form-control" asp-for="Engine" type="text"/>
                <span asp-validation-for="Engine" class="text-danger"></span>
            </div>

            <div class="form-group mb-3">
                <label asp-for="Year">Production year</label>
                <input class="form-control" type="text" asp-for="Year"/>
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>

            <div class="form-group mb-3">
                <button type="submit" class="btn btn-primary">Create</button>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

CarRental.Presentation/Views/Car/Delete.cshtml
@model CarRental.Application.Dto.CarDto

<hr />

<h2>Delete car</h2>

<h4>Are you sure you want to delete the car?</h4>

<div>
    <h5>Car: @Model.Brand @Model.Model</h5>
    <p>Price per day: @Model.PricePerDay zł</p>
    <p>Description: @Model.Description</p>
</div>

<form asp-action="Delete" method="post">
    @Html.AntiForgeryToken() 
    <input type="hidden" asp-for="Id" /> <!-- Hidden field that allows to delete car by Id-->
    <button type="submit" class="btn btn-danger">Delete</button> 
    <a asp-action="Index" class="btn btn-secondary">Cancel</a> 
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

CarRental.Presentation/Views/Car/Details.cshtml
@model CreateCarViewModel

<h2>Car details</h2>

@if (Model.ImageUrls.Any())
{
    foreach (var url in Model.ImageUrls)
    {
        <img src="@Url.Content(url)" alt="@Model.Brand @Model.Model" style="max-width: 300px;" />
    }
}
else
{
    <p>No images available for this car.</p>
}


<p><strong>Brand:</strong> @Model.Brand</p>
<p><strong>Model:</strong> @Model.Model</p>
<p><strong>Price per day:</strong> @Model.PricePerDay zł</p>

@if (!string.IsNullOrEmpty(Model.Description))
{
    <p><strong>Description:</strong> @Model.Description</p>
}

@if (!string.IsNullOrEmpty(Model.Engine))
{
    <p><strong>Engine:</strong> @Model.Engine</p>
}

@if (Model.Year > 0)
{
    <p><strong>Production year:</strong> @Model.Year</p>
}

<a asp-controller="Car" asp-action="Index" class="btn btn-secondary">Back to list</a>

CarRental.Presentation/Views/Car/Edit.cshtml
@model CarRental.Presentation.Models.EditCarViewModel

<h2>Edit car</h2>

<hr />

<div class="row">
    <div class="col-md-4">

        <form asp-action="Edit" method="post" enctype="multipart/form-data">
            @Html.AntiForgeryToken()

            <div class="form-group">
                <label asp-for="Brand">Brand</label>
                <input class="form-control" type="text" asp-for="Brand" />
                <span asp-validation-for="Brand" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Model">Model</label>
                <input class="form-control" type="text" asp-for="Model" />
                <span asp-validation-for="Model" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="PricePerDay">Price per day</label>
                <input class="form-control" type="text" asp-for="PricePerDay" />
                <span asp-validation-for="PricePerDay" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="IsAvailable">Is Available</label>
                <input asp-for="IsAvailable" type="checkbox" />
            </div>

            <div class="form-group">
                <label asp-for="NewImages">Change images</label>
                <input class="form-control" asp-for="NewImages" type="file" multiple />
                <span asp-validation-for="NewImages" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Description">Description</label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Engine">Engine</label>
                <input class="form-control" type="text" asp-for="Engine" />
                <span asp-validation-for="Engine" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Year">Production year</label>
                <input class="form-control" type="text" asp-for="Year" />
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>

            <button type="submit" class="btn btn-primary">Save changes</button>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

CarRental.Presentation/Views/Car/Index.cshtml
@model ICollection<CarRental.Presentation.Models.CreateCarViewModel>

<h2 class="text-center">Available cars</h2>
<div class="row">
    @foreach (var car in Model)
    {
        <div class="col-md-4">
            <div class="card mb-4">
                @{
                    var firstImg = car.ImageUrls?.FirstOrDefault() ?? "/images/default-car.jpg";
                }
                <img src="@Url.Content(firstImg)" class="card-img-top" alt="@car.Brand @car.Model" />
                <div class="card-body">
                    <h5 class="card-title">@car.Brand @car.Model</h5>
                    <p class="card-text">Price per day: <strong>@car.PricePerDay</strong></p>

                    @if (car.IsAvailable)
                    {
                        @if (User.Identity.IsAuthenticated)
                        {
                            <!-- If user authenticated, display reservation button -->
                            <a asp-controller="Reservation" asp-action="Create" asp-route-carId="@car.Id" class="btn btn-primary btn-block">Reservation</a>
                        }
                        else
                        {
                            <!-- If user not authenticated, display information to log in-->
                            <p class="text-muted text-center">Log in to reserve</p>
                        }
                    }
                    else
                    {
                        <!-- If car not available, display "Not available" -->
                        <p class="text-danger text-center">Not available</p>
                    }

                    @if (User.IsInRole("Admin")) 
                    {
                        <!-- If user is Admin, display delete and edit buttons -->
                        <a asp-controller="Car" asp-action="Edit" asp-route-id="@car.Id" class="btn btn-warning">Edit</a>
                        <a asp-controller="Car" asp-action="Delete" asp-route-id="@car.Id" class="btn btn-danger">Delete</a>
                    }
                </div>
            </div>
        </div>
    }
</div>